// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const rebindTransfer = table("rebind_transfer", {
  chainId: db.uint64('chain_id'),
  token: db.address('token'),
  from: db.address('from'),
  to: db.address('to'),
  value: db.uint256('value'),
  blockNumber: db.uint256('block_number'),
  txnHash: db.bytes32('txn_hash'),
})
